#ifndef LNCPU_EMU_OPCODES_H
#define LNCPU_EMU_OPCODES_H

#include <stdint.h>

struct opcode_info_t {
	const uint8_t opcode; 
	const char *mnemonic;
	const uint8_t data_length;
	const uint8_t clock_cycles;
};

enum Opcode {	OP_NOP =	0x0, 
	OP_HLT =	0x1, 
	OP__BRK_ =	0x2, 
	OP_INT =	0x3, 
	OP_MOV_CST_RA =	0x4, 
	OP_MOV_CST_RB =	0x5, 
	OP_MOV_CST_RC =	0x6, 
	OP_MOV_CST_RD =	0x7, 
	OP_MOV_CST_SP =	0x8, 
	OP_MOV_CST_SS =	0x9, 
	OP_MOV_CST_DS =	0xa, 
	OP_MOV_CST_BP =	0xb, 
	OP_MOV_SS_RD =	0xc, 
	OP_MOV_SP_RD =	0xd, 
	OP_MOV_SP_BP =	0xe, 
	OP_MOV_BP_SP =	0xf, 
	OP_MOV_DS_RD =	0x10, 
	OP_MOV_RA_RB =	0x11, 
	OP_MOV_RA_RC =	0x12, 
	OP_MOV_RA_RD =	0x13, 
	OP_MOV_RB_RA =	0x14, 
	OP_MOV_RB_RC =	0x15, 
	OP_MOV_RB_RD =	0x16, 
	OP_MOV_RC_RA =	0x17, 
	OP_MOV_RC_RB =	0x18, 
	OP_MOV_RC_RD =	0x19, 
	OP_MOV_RD_RA =	0x1a, 
	OP_MOV_RD_RB =	0x1b, 
	OP_MOV_RD_RC =	0x1c, 
	OP_MOV_RD_SS =	0x1d, 
	OP_MOV_RD_SP =	0x1e, 
	OP_MOV_RD_DS =	0x1f, 
	OP_MOV_IBPOFFSET_RA =	0x20, 
	OP_MOV_IBPOFFSET_RB =	0x21, 
	OP_MOV_IBPOFFSET_RC =	0x22, 
	OP_MOV_IBPOFFSET_RD =	0x23, 
	OP_MOV_RA_IBPOFFSET =	0x24, 
	OP_MOV_RB_IBPOFFSET =	0x25, 
	OP_MOV_RC_IBPOFFSET =	0x26, 
	OP_MOV_RD_IBPOFFSET =	0x27, 
	OP_MOV_CST_IBPOFFSET =	0x28, 
	OP_MOV_RA_DATAP =	0x29, 
	OP_MOV_RB_DATAP =	0x2a, 
	OP_MOV_RC_DATAP =	0x2b, 
	OP_MOV_RD_DATAP =	0x2c, 
	OP_MOV_DATAP_RA =	0x2d, 
	OP_MOV_DATAP_RB =	0x2e, 
	OP_MOV_DATAP_RC =	0x2f, 
	OP_MOV_DATAP_RD =	0x30, 
	OP_MOV_CST_DATAP =	0x31, 
	OP_MOV_RA_IRCRD =	0x32, 
	OP_MOV_RB_IRCRD =	0x33, 
	OP_MOV_RC_IRCRD =	0x34, 
	OP_MOV_RD_IRCRD =	0x35, 
	OP_MOV_IRCRD_RA =	0x36, 
	OP_MOV_IRCRD_RB =	0x37, 
	OP_MOV_IRCRD_RC =	0x38, 
	OP_MOV_IRCRD_RD =	0x39, 
	OP_MOV_CST_IRCRD =	0x3a, 
	OP_MOV_RA_ABS =	0x3b, 
	OP_MOV_RB_ABS =	0x3c, 
	OP_MOV_RC_ABS =	0x3d, 
	OP_MOV_RD_ABS =	0x3e, 
	OP_MOV_ABS_RA =	0x3f, 
	OP_MOV_ABS_RB =	0x40, 
	OP_MOV_ABS_RC =	0x41, 
	OP_MOV_ABS_RD =	0x42, 
	OP_MOV_CST_ABS =	0x43, 
	OP_MOV_DATAP_DATAP =	0x44, 
	OP_MOV_IRD_RA =	0x45, 
	OP_MOV_IRD_RB =	0x46, 
	OP_MOV_IRD_RC =	0x47, 
	OP_MOV_IRD_RD =	0x48, 
	OP_MOV_RA_IRD =	0x49, 
	OP_MOV_RB_IRD =	0x4a, 
	OP_MOV_RC_IRD =	0x4b, 
	OP_MOV_RD_IRD =	0x4c, 
	OP_MOV_CST_IRD =	0x4d, 
	OP_PUSH_RA =	0x4e, 
	OP_PUSH_RB =	0x4f, 
	OP_PUSH_RC =	0x50, 
	OP_PUSH_RD =	0x51, 
	OP_PUSH_DATAP =	0x52, 
	OP_PUSH_IRD =	0x53, 
	OP_PUSH_IRCRD =	0x54, 
	OP_PUSH_ABS =	0x55, 
	OP_PUSH_CST =	0x56, 
	OP_PUSH_BP =	0x57, 
	OP_PUSH_DS =	0x58, 
	OP_POP_RA =	0x59, 
	OP_POP_RB =	0x5a, 
	OP_POP_RC =	0x5b, 
	OP_POP_RD =	0x5c, 
	OP_POP_DATAP =	0x5d, 
	OP_POP_IRD =	0x5e, 
	OP_POP_IRCRD =	0x5f, 
	OP_POP_ABS =	0x60, 
	OP_POP_BP =	0x61, 
	OP_POP_DS =	0x62, 
	OP_ADD_RA_RA =	0x63, 
	OP_ADD_RA_RB =	0x64, 
	OP_ADD_RA_RC =	0x65, 
	OP_ADD_RA_RD =	0x66, 
	OP_ADD_RB_RA =	0x67, 
	OP_ADD_RB_RB =	0x68, 
	OP_ADD_RB_RC =	0x69, 
	OP_ADD_RB_RD =	0x6a, 
	OP_ADD_RC_RA =	0x6b, 
	OP_ADD_RC_RB =	0x6c, 
	OP_ADD_RC_RC =	0x6d, 
	OP_ADD_RC_RD =	0x6e, 
	OP_ADD_RD_RA =	0x6f, 
	OP_ADD_RD_RB =	0x70, 
	OP_ADD_RD_RC =	0x71, 
	OP_ADD_RD_RD =	0x72, 
	OP_ADD_RA_CST =	0x73, 
	OP_ADD_RB_CST =	0x74, 
	OP_ADD_RC_CST =	0x75, 
	OP_ADD_RD_CST =	0x76, 
	OP_ADD_SP_CST =	0x77, 
	OP_ADD_BP_CST =	0x78, 
	OP_SUB_RA_RA =	0x79, 
	OP_SUB_RA_RB =	0x7a, 
	OP_SUB_RA_RC =	0x7b, 
	OP_SUB_RA_RD =	0x7c, 
	OP_SUB_RB_RA =	0x7d, 
	OP_SUB_RB_RB =	0x7e, 
	OP_SUB_RB_RC =	0x7f, 
	OP_SUB_RB_RD =	0x80, 
	OP_SUB_RC_RA =	0x81, 
	OP_SUB_RC_RB =	0x82, 
	OP_SUB_RC_RC =	0x83, 
	OP_SUB_RC_RD =	0x84, 
	OP_SUB_RD_RA =	0x85, 
	OP_SUB_RD_RB =	0x86, 
	OP_SUB_RD_RC =	0x87, 
	OP_SUB_RD_RD =	0x88, 
	OP_SUB_RA_CST =	0x89, 
	OP_SUB_RB_CST =	0x8a, 
	OP_SUB_RC_CST =	0x8b, 
	OP_SUB_RD_CST =	0x8c, 
	OP_SUB_SP_CST =	0x8d, 
	OP_SUB_BP_CST =	0x8e, 
	OP_CMP_RA_RA =	0x8f, 
	OP_CMP_RA_RB =	0x90, 
	OP_CMP_RA_RC =	0x91, 
	OP_CMP_RA_RD =	0x92, 
	OP_CMP_RB_RA =	0x93, 
	OP_CMP_RB_RB =	0x94, 
	OP_CMP_RB_RC =	0x95, 
	OP_CMP_RB_RD =	0x96, 
	OP_CMP_RC_RA =	0x97, 
	OP_CMP_RC_RB =	0x98, 
	OP_CMP_RC_RC =	0x99, 
	OP_CMP_RC_RD =	0x9a, 
	OP_CMP_RD_RA =	0x9b, 
	OP_CMP_RD_RB =	0x9c, 
	OP_CMP_RD_RC =	0x9d, 
	OP_CMP_RD_RD =	0x9e, 
	OP_CMP_RA_CST =	0x9f, 
	OP_CMP_RB_CST =	0xa0, 
	OP_CMP_RC_CST =	0xa1, 
	OP_CMP_RD_CST =	0xa2, 
	OP_OR_RA_RA =	0xa3, 
	OP_OR_RA_RB =	0xa4, 
	OP_OR_RA_RC =	0xa5, 
	OP_OR_RA_RD =	0xa6, 
	OP_OR_RB_RA =	0xa7, 
	OP_OR_RB_RB =	0xa8, 
	OP_OR_RB_RC =	0xa9, 
	OP_OR_RB_RD =	0xaa, 
	OP_OR_RC_RA =	0xab, 
	OP_OR_RC_RB =	0xac, 
	OP_OR_RC_RC =	0xad, 
	OP_OR_RC_RD =	0xae, 
	OP_OR_RD_RA =	0xaf, 
	OP_OR_RD_RB =	0xb0, 
	OP_OR_RD_RC =	0xb1, 
	OP_OR_RD_RD =	0xb2, 
	OP_OR_RA_CST =	0xb3, 
	OP_OR_RB_CST =	0xb4, 
	OP_OR_RC_CST =	0xb5, 
	OP_OR_RD_CST =	0xb6, 
	OP_AND_RA_RA =	0xb7, 
	OP_AND_RA_RB =	0xb8, 
	OP_AND_RA_RC =	0xb9, 
	OP_AND_RA_RD =	0xba, 
	OP_AND_RB_RA =	0xbb, 
	OP_AND_RB_RB =	0xbc, 
	OP_AND_RB_RC =	0xbd, 
	OP_AND_RB_RD =	0xbe, 
	OP_AND_RC_RA =	0xbf, 
	OP_AND_RC_RB =	0xc0, 
	OP_AND_RC_RC =	0xc1, 
	OP_AND_RC_RD =	0xc2, 
	OP_AND_RD_RA =	0xc3, 
	OP_AND_RD_RB =	0xc4, 
	OP_AND_RD_RC =	0xc5, 
	OP_AND_RD_RD =	0xc6, 
	OP_AND_RA_CST =	0xc7, 
	OP_AND_RB_CST =	0xc8, 
	OP_AND_RC_CST =	0xc9, 
	OP_AND_RD_CST =	0xca, 
	OP_XOR_RA_RA =	0xcb, 
	OP_XOR_RA_RB =	0xcc, 
	OP_XOR_RA_RC =	0xcd, 
	OP_XOR_RA_RD =	0xce, 
	OP_XOR_RB_RA =	0xcf, 
	OP_XOR_RB_RB =	0xd0, 
	OP_XOR_RB_RC =	0xd1, 
	OP_XOR_RB_RD =	0xd2, 
	OP_XOR_RC_RA =	0xd3, 
	OP_XOR_RC_RB =	0xd4, 
	OP_XOR_RC_RC =	0xd5, 
	OP_XOR_RC_RD =	0xd6, 
	OP_XOR_RD_RA =	0xd7, 
	OP_XOR_RD_RB =	0xd8, 
	OP_XOR_RD_RC =	0xd9, 
	OP_XOR_RD_RD =	0xda, 
	OP_XOR_RA_CST =	0xdb, 
	OP_XOR_RB_CST =	0xdc, 
	OP_XOR_RC_CST =	0xdd, 
	OP_XOR_RD_CST =	0xde, 
	OP_NOT_RA =	0xdf, 
	OP_NOT_RB =	0xe0, 
	OP_NOT_RC =	0xe1, 
	OP_NOT_RD =	0xe2, 
	OP_INC_RA =	0xe3, 
	OP_INC_RB =	0xe4, 
	OP_INC_RC =	0xe5, 
	OP_INC_RD =	0xe6, 
	OP_DEC_RA =	0xe7, 
	OP_DEC_RB =	0xe8, 
	OP_DEC_RC =	0xe9, 
	OP_DEC_RD =	0xea, 
	OP_SHL_RA =	0xeb, 
	OP_SHR_RA =	0xec, 
	OP_JC_CST =	0xed, 
	OP_JN_CST =	0xee, 
	OP_JZ_CST =	0xef, 
	OP_GOTO_CST =	0xf0, 
	OP_LJC_DCST =	0xf1, 
	OP_LJN_DCST =	0xf2, 
	OP_LJZ_DCST =	0xf3, 
	OP_LGOTO_DCST =	0xf4, 
	OP_LGOTO_RCRD =	0xf5, 
	OP_LCALL_DCST =	0xf6, 
	OP_LCALL_RCRD =	0xf7, 
	OP_RET =	0xf8, 
	OP_RET_CST =	0xf9, 
	OP_IRET =	0xfa, 
	OP_CID =	0xfb, 
	OP_SID =	0xfc, 
	OP_CLC =	0xfd, 
	OP_SEC =	0xfe, 

};

static const struct opcode_info_t opcode_info[] = {
	{OP_NOP, "nop", 1, 1},
	{OP_HLT, "hlt", 1, 1},
	{OP__BRK_, "$brk$", 2, 7},
	{OP_INT, "int", 1, 7},
	{OP_MOV_CST_RA, "mov_cst_ra", 2, 2},
	{OP_MOV_CST_RB, "mov_cst_rb", 2, 2},
	{OP_MOV_CST_RC, "mov_cst_rc", 2, 2},
	{OP_MOV_CST_RD, "mov_cst_rd", 2, 2},
	{OP_MOV_CST_SP, "mov_cst_sp", 2, 2},
	{OP_MOV_CST_SS, "mov_cst_ss", 2, 2},
	{OP_MOV_CST_DS, "mov_cst_ds", 2, 2},
	{OP_MOV_CST_BP, "mov_cst_bp", 2, 2},
	{OP_MOV_SS_RD, "mov_ss_rd", 1, 1},
	{OP_MOV_SP_RD, "mov_sp_rd", 1, 1},
	{OP_MOV_SP_BP, "mov_sp_bp", 1, 1},
	{OP_MOV_BP_SP, "mov_bp_sp", 1, 1},
	{OP_MOV_DS_RD, "mov_ds_rd", 1, 1},
	{OP_MOV_RA_RB, "mov_ra_rb", 1, 1},
	{OP_MOV_RA_RC, "mov_ra_rc", 1, 1},
	{OP_MOV_RA_RD, "mov_ra_rd", 1, 1},
	{OP_MOV_RB_RA, "mov_rb_ra", 1, 1},
	{OP_MOV_RB_RC, "mov_rb_rc", 1, 1},
	{OP_MOV_RB_RD, "mov_rb_rd", 1, 1},
	{OP_MOV_RC_RA, "mov_rc_ra", 1, 1},
	{OP_MOV_RC_RB, "mov_rc_rb", 1, 1},
	{OP_MOV_RC_RD, "mov_rc_rd", 1, 1},
	{OP_MOV_RD_RA, "mov_rd_ra", 1, 1},
	{OP_MOV_RD_RB, "mov_rd_rb", 1, 1},
	{OP_MOV_RD_RC, "mov_rd_rc", 1, 1},
	{OP_MOV_RD_SS, "mov_rd_ss", 1, 1},
	{OP_MOV_RD_SP, "mov_rd_sp", 1, 1},
	{OP_MOV_RD_DS, "mov_rd_ds", 1, 1},
	{OP_MOV_IBPOFFSET_RA, "mov_ibpoffset_ra", 2, 4},
	{OP_MOV_IBPOFFSET_RB, "mov_ibpoffset_rb", 2, 4},
	{OP_MOV_IBPOFFSET_RC, "mov_ibpoffset_rc", 2, 4},
	{OP_MOV_IBPOFFSET_RD, "mov_ibpoffset_rd", 2, 4},
	{OP_MOV_RA_IBPOFFSET, "mov_ra_ibpoffset", 2, 4},
	{OP_MOV_RB_IBPOFFSET, "mov_rb_ibpoffset", 2, 4},
	{OP_MOV_RC_IBPOFFSET, "mov_rc_ibpoffset", 2, 4},
	{OP_MOV_RD_IBPOFFSET, "mov_rd_ibpoffset", 2, 4},
	{OP_MOV_CST_IBPOFFSET, "mov_cst_ibpoffset", 3, 5},
	{OP_MOV_RA_DATAP, "mov_ra_datap", 2, 2},
	{OP_MOV_RB_DATAP, "mov_rb_datap", 2, 2},
	{OP_MOV_RC_DATAP, "mov_rc_datap", 2, 2},
	{OP_MOV_RD_DATAP, "mov_rd_datap", 2, 2},
	{OP_MOV_DATAP_RA, "mov_datap_ra", 2, 2},
	{OP_MOV_DATAP_RB, "mov_datap_rb", 2, 2},
	{OP_MOV_DATAP_RC, "mov_datap_rc", 2, 2},
	{OP_MOV_DATAP_RD, "mov_datap_rd", 2, 2},
	{OP_MOV_CST_DATAP, "mov_cst_datap", 3, 3},
	{OP_MOV_RA_IRCRD, "mov_ra_ircrd", 1, 3},
	{OP_MOV_RB_IRCRD, "mov_rb_ircrd", 1, 3},
	{OP_MOV_RC_IRCRD, "mov_rc_ircrd", 1, 3},
	{OP_MOV_RD_IRCRD, "mov_rd_ircrd", 1, 3},
	{OP_MOV_IRCRD_RA, "mov_ircrd_ra", 1, 3},
	{OP_MOV_IRCRD_RB, "mov_ircrd_rb", 1, 3},
	{OP_MOV_IRCRD_RC, "mov_ircrd_rc", 1, 3},
	{OP_MOV_IRCRD_RD, "mov_ircrd_rd", 1, 3},
	{OP_MOV_CST_IRCRD, "mov_cst_ircrd", 2, 4},
	{OP_MOV_RA_ABS, "mov_ra_abs", 3, 3},
	{OP_MOV_RB_ABS, "mov_rb_abs", 3, 3},
	{OP_MOV_RC_ABS, "mov_rc_abs", 3, 3},
	{OP_MOV_RD_ABS, "mov_rd_abs", 3, 3},
	{OP_MOV_ABS_RA, "mov_abs_ra", 3, 3},
	{OP_MOV_ABS_RB, "mov_abs_rb", 3, 3},
	{OP_MOV_ABS_RC, "mov_abs_rc", 3, 3},
	{OP_MOV_ABS_RD, "mov_abs_rd", 3, 3},
	{OP_MOV_CST_ABS, "mov_cst_abs", 4, 4},
	{OP_MOV_DATAP_DATAP, "mov_datap_datap", 3, 4},
	{OP_MOV_IRD_RA, "mov_ird_ra", 1, 2},
	{OP_MOV_IRD_RB, "mov_ird_rb", 1, 2},
	{OP_MOV_IRD_RC, "mov_ird_rc", 1, 2},
	{OP_MOV_IRD_RD, "mov_ird_rd", 1, 2},
	{OP_MOV_RA_IRD, "mov_ra_ird", 1, 2},
	{OP_MOV_RB_IRD, "mov_rb_ird", 1, 2},
	{OP_MOV_RC_IRD, "mov_rc_ird", 1, 2},
	{OP_MOV_RD_IRD, "mov_rd_ird", 1, 2},
	{OP_MOV_CST_IRD, "mov_cst_ird", 2, 3},
	{OP_PUSH_RA, "push_ra", 1, 2},
	{OP_PUSH_RB, "push_rb", 1, 2},
	{OP_PUSH_RC, "push_rc", 1, 2},
	{OP_PUSH_RD, "push_rd", 1, 2},
	{OP_PUSH_DATAP, "push_datap", 2, 4},
	{OP_PUSH_IRD, "push_ird", 1, 4},
	{OP_PUSH_IRCRD, "push_ircrd", 1, 5},
	{OP_PUSH_ABS, "push_abs", 3, 5},
	{OP_PUSH_CST, "push_cst", 2, 2},
	{OP_PUSH_BP, "push_bp", 1, 2},
	{OP_PUSH_DS, "push_ds", 1, 2},
	{OP_POP_RA, "pop_ra", 1, 1},
	{OP_POP_RB, "pop_rb", 1, 1},
	{OP_POP_RC, "pop_rc", 1, 1},
	{OP_POP_RD, "pop_rd", 1, 1},
	{OP_POP_DATAP, "pop_datap", 2, 3},
	{OP_POP_IRD, "pop_ird", 1, 3},
	{OP_POP_IRCRD, "pop_ircrd", 1, 4},
	{OP_POP_ABS, "pop_abs", 3, 4},
	{OP_POP_BP, "pop_bp", 1, 1},
	{OP_POP_DS, "pop_ds", 1, 1},
	{OP_ADD_RA_RA, "add_ra_ra", 1, 1},
	{OP_ADD_RA_RB, "add_ra_rb", 1, 1},
	{OP_ADD_RA_RC, "add_ra_rc", 1, 1},
	{OP_ADD_RA_RD, "add_ra_rd", 1, 1},
	{OP_ADD_RB_RA, "add_rb_ra", 1, 1},
	{OP_ADD_RB_RB, "add_rb_rb", 1, 1},
	{OP_ADD_RB_RC, "add_rb_rc", 1, 1},
	{OP_ADD_RB_RD, "add_rb_rd", 1, 1},
	{OP_ADD_RC_RA, "add_rc_ra", 1, 1},
	{OP_ADD_RC_RB, "add_rc_rb", 1, 1},
	{OP_ADD_RC_RC, "add_rc_rc", 1, 1},
	{OP_ADD_RC_RD, "add_rc_rd", 1, 1},
	{OP_ADD_RD_RA, "add_rd_ra", 1, 1},
	{OP_ADD_RD_RB, "add_rd_rb", 1, 1},
	{OP_ADD_RD_RC, "add_rd_rc", 1, 1},
	{OP_ADD_RD_RD, "add_rd_rd", 1, 1},
	{OP_ADD_RA_CST, "add_ra_cst", 2, 2},
	{OP_ADD_RB_CST, "add_rb_cst", 2, 2},
	{OP_ADD_RC_CST, "add_rc_cst", 2, 2},
	{OP_ADD_RD_CST, "add_rd_cst", 2, 2},
	{OP_ADD_SP_CST, "add_sp_cst", 2, 2},
	{OP_ADD_BP_CST, "add_bp_cst", 2, 2},
	{OP_SUB_RA_RA, "sub_ra_ra", 1, 1},
	{OP_SUB_RA_RB, "sub_ra_rb", 1, 1},
	{OP_SUB_RA_RC, "sub_ra_rc", 1, 1},
	{OP_SUB_RA_RD, "sub_ra_rd", 1, 1},
	{OP_SUB_RB_RA, "sub_rb_ra", 1, 1},
	{OP_SUB_RB_RB, "sub_rb_rb", 1, 1},
	{OP_SUB_RB_RC, "sub_rb_rc", 1, 1},
	{OP_SUB_RB_RD, "sub_rb_rd", 1, 1},
	{OP_SUB_RC_RA, "sub_rc_ra", 1, 1},
	{OP_SUB_RC_RB, "sub_rc_rb", 1, 1},
	{OP_SUB_RC_RC, "sub_rc_rc", 1, 1},
	{OP_SUB_RC_RD, "sub_rc_rd", 1, 1},
	{OP_SUB_RD_RA, "sub_rd_ra", 1, 1},
	{OP_SUB_RD_RB, "sub_rd_rb", 1, 1},
	{OP_SUB_RD_RC, "sub_rd_rc", 1, 1},
	{OP_SUB_RD_RD, "sub_rd_rd", 1, 1},
	{OP_SUB_RA_CST, "sub_ra_cst", 2, 2},
	{OP_SUB_RB_CST, "sub_rb_cst", 2, 2},
	{OP_SUB_RC_CST, "sub_rc_cst", 2, 2},
	{OP_SUB_RD_CST, "sub_rd_cst", 2, 2},
	{OP_SUB_SP_CST, "sub_sp_cst", 2, 2},
	{OP_SUB_BP_CST, "sub_bp_cst", 2, 2},
	{OP_CMP_RA_RA, "cmp_ra_ra", 1, 1},
	{OP_CMP_RA_RB, "cmp_ra_rb", 1, 1},
	{OP_CMP_RA_RC, "cmp_ra_rc", 1, 1},
	{OP_CMP_RA_RD, "cmp_ra_rd", 1, 1},
	{OP_CMP_RB_RA, "cmp_rb_ra", 1, 1},
	{OP_CMP_RB_RB, "cmp_rb_rb", 1, 1},
	{OP_CMP_RB_RC, "cmp_rb_rc", 1, 1},
	{OP_CMP_RB_RD, "cmp_rb_rd", 1, 1},
	{OP_CMP_RC_RA, "cmp_rc_ra", 1, 1},
	{OP_CMP_RC_RB, "cmp_rc_rb", 1, 1},
	{OP_CMP_RC_RC, "cmp_rc_rc", 1, 1},
	{OP_CMP_RC_RD, "cmp_rc_rd", 1, 1},
	{OP_CMP_RD_RA, "cmp_rd_ra", 1, 1},
	{OP_CMP_RD_RB, "cmp_rd_rb", 1, 1},
	{OP_CMP_RD_RC, "cmp_rd_rc", 1, 1},
	{OP_CMP_RD_RD, "cmp_rd_rd", 1, 1},
	{OP_CMP_RA_CST, "cmp_ra_cst", 2, 2},
	{OP_CMP_RB_CST, "cmp_rb_cst", 2, 2},
	{OP_CMP_RC_CST, "cmp_rc_cst", 2, 2},
	{OP_CMP_RD_CST, "cmp_rd_cst", 2, 2},
	{OP_OR_RA_RA, "or_ra_ra", 1, 1},
	{OP_OR_RA_RB, "or_ra_rb", 1, 1},
	{OP_OR_RA_RC, "or_ra_rc", 1, 1},
	{OP_OR_RA_RD, "or_ra_rd", 1, 1},
	{OP_OR_RB_RA, "or_rb_ra", 1, 1},
	{OP_OR_RB_RB, "or_rb_rb", 1, 1},
	{OP_OR_RB_RC, "or_rb_rc", 1, 1},
	{OP_OR_RB_RD, "or_rb_rd", 1, 1},
	{OP_OR_RC_RA, "or_rc_ra", 1, 1},
	{OP_OR_RC_RB, "or_rc_rb", 1, 1},
	{OP_OR_RC_RC, "or_rc_rc", 1, 1},
	{OP_OR_RC_RD, "or_rc_rd", 1, 1},
	{OP_OR_RD_RA, "or_rd_ra", 1, 1},
	{OP_OR_RD_RB, "or_rd_rb", 1, 1},
	{OP_OR_RD_RC, "or_rd_rc", 1, 1},
	{OP_OR_RD_RD, "or_rd_rd", 1, 1},
	{OP_OR_RA_CST, "or_ra_cst", 2, 2},
	{OP_OR_RB_CST, "or_rb_cst", 2, 2},
	{OP_OR_RC_CST, "or_rc_cst", 2, 2},
	{OP_OR_RD_CST, "or_rd_cst", 2, 2},
	{OP_AND_RA_RA, "and_ra_ra", 1, 1},
	{OP_AND_RA_RB, "and_ra_rb", 1, 1},
	{OP_AND_RA_RC, "and_ra_rc", 1, 1},
	{OP_AND_RA_RD, "and_ra_rd", 1, 1},
	{OP_AND_RB_RA, "and_rb_ra", 1, 1},
	{OP_AND_RB_RB, "and_rb_rb", 1, 1},
	{OP_AND_RB_RC, "and_rb_rc", 1, 1},
	{OP_AND_RB_RD, "and_rb_rd", 1, 1},
	{OP_AND_RC_RA, "and_rc_ra", 1, 1},
	{OP_AND_RC_RB, "and_rc_rb", 1, 1},
	{OP_AND_RC_RC, "and_rc_rc", 1, 1},
	{OP_AND_RC_RD, "and_rc_rd", 1, 1},
	{OP_AND_RD_RA, "and_rd_ra", 1, 1},
	{OP_AND_RD_RB, "and_rd_rb", 1, 1},
	{OP_AND_RD_RC, "and_rd_rc", 1, 1},
	{OP_AND_RD_RD, "and_rd_rd", 1, 1},
	{OP_AND_RA_CST, "and_ra_cst", 2, 2},
	{OP_AND_RB_CST, "and_rb_cst", 2, 2},
	{OP_AND_RC_CST, "and_rc_cst", 2, 2},
	{OP_AND_RD_CST, "and_rd_cst", 2, 2},
	{OP_XOR_RA_RA, "xor_ra_ra", 1, 1},
	{OP_XOR_RA_RB, "xor_ra_rb", 1, 1},
	{OP_XOR_RA_RC, "xor_ra_rc", 1, 1},
	{OP_XOR_RA_RD, "xor_ra_rd", 1, 1},
	{OP_XOR_RB_RA, "xor_rb_ra", 1, 1},
	{OP_XOR_RB_RB, "xor_rb_rb", 1, 1},
	{OP_XOR_RB_RC, "xor_rb_rc", 1, 1},
	{OP_XOR_RB_RD, "xor_rb_rd", 1, 1},
	{OP_XOR_RC_RA, "xor_rc_ra", 1, 1},
	{OP_XOR_RC_RB, "xor_rc_rb", 1, 1},
	{OP_XOR_RC_RC, "xor_rc_rc", 1, 1},
	{OP_XOR_RC_RD, "xor_rc_rd", 1, 1},
	{OP_XOR_RD_RA, "xor_rd_ra", 1, 1},
	{OP_XOR_RD_RB, "xor_rd_rb", 1, 1},
	{OP_XOR_RD_RC, "xor_rd_rc", 1, 1},
	{OP_XOR_RD_RD, "xor_rd_rd", 1, 1},
	{OP_XOR_RA_CST, "xor_ra_cst", 2, 2},
	{OP_XOR_RB_CST, "xor_rb_cst", 2, 2},
	{OP_XOR_RC_CST, "xor_rc_cst", 2, 2},
	{OP_XOR_RD_CST, "xor_rd_cst", 2, 2},
	{OP_NOT_RA, "not_ra", 1, 1},
	{OP_NOT_RB, "not_rb", 1, 1},
	{OP_NOT_RC, "not_rc", 1, 1},
	{OP_NOT_RD, "not_rd", 1, 1},
	{OP_INC_RA, "inc_ra", 1, 1},
	{OP_INC_RB, "inc_rb", 1, 1},
	{OP_INC_RC, "inc_rc", 1, 1},
	{OP_INC_RD, "inc_rd", 1, 1},
	{OP_DEC_RA, "dec_ra", 1, 1},
	{OP_DEC_RB, "dec_rb", 1, 1},
	{OP_DEC_RC, "dec_rc", 1, 1},
	{OP_DEC_RD, "dec_rd", 1, 1},
	{OP_SHL_RA, "shl_ra", 1, 1},
	{OP_SHR_RA, "shr_ra", 1, 1},
	{OP_JC_CST, "jc_cst", 2, 3},
	{OP_JN_CST, "jn_cst", 2, 3},
	{OP_JZ_CST, "jz_cst", 2, 3},
	{OP_GOTO_CST, "goto_cst", 2, 3},
	{OP_LJC_DCST, "ljc_dcst", 3, 4},
	{OP_LJN_DCST, "ljn_dcst", 3, 4},
	{OP_LJZ_DCST, "ljz_dcst", 3, 4},
	{OP_LGOTO_DCST, "lgoto_dcst", 3, 4},
	{OP_LGOTO_RCRD, "lgoto_rcrd", 1, 4},
	{OP_LCALL_DCST, "lcall_dcst", 3, 6},
	{OP_LCALL_RCRD, "lcall_rcrd", 1, 6},
	{OP_RET, "ret", 1, 4},
	{OP_RET_CST, "ret_cst", 2, 6},
	{OP_IRET, "iret", 1, 5},
	{OP_CID, "cid", 1, 1},
	{OP_SID, "sid", 1, 1},
	{OP_CLC, "clc", 1, 1},
	{OP_SEC, "sec", 1, 1},
};

#endif //LNCPU_EMU_OPCODES_H
